#ifndef EXTERNAL_CONSTANTS
#define EXTERNAL_CONSTANTS
#define GAME_DURATION_TERMINAL
#define GAME_DURATION 20
#define MISSED_MINE_PENALTY -0.5
#define SHOT_MINE_REWARD 200
#define MINE_LIVE_LOOPS 10
#define SPRAYING_PENALTY -0.3
#endif