#ifndef EXTERNAL_CONSTANTS
#define EXTERNAL_CONSTANTS
#define GAME_DURATION_TERMINAL
#define GAME_DURATION 200
#define GAME_OVER_SCORE 200
#define FORTRESS_SHOT_SCORE 200
#define SHOT_BY_FORTRESS_PENALTY 200
#define MAX_SHIP_DAMAGE 200
#define FORTRESS_LIVES 199
#endif