#ifndef EXTERNAL_CONSTANTS
#define EXTERNAL_CONSTANTS
#define GAME_DURATION 20
#define MISSED_MINE_PENALTY -200
#define COLLECTED_MINE_REWARD 500
#define MAX_SQUARE_STEPS 500
#define MAX_SQUARES_TERMINAL
#define MAX_SQUARES 1
#define MISSED_MINE_TERMINAL
#define GAME_OVER_SCORE -50
#define FORTRESS_SHOT_SCORE 400
#define MAX_SHIP_DAMAGE 1
// #define GAME_DURATION_TERMINAL
#define SHOT_BY_FORTRESS_PENALTY -800
#endif
