#ifndef EXTERNAL_CONSTANTS
#define EXTERNAL_CONSTANTS
#define GAME_DURATION_TERMINAL
#define GAME_DURATION 200
#define MISSED_MINE_PENALTY -2
#define COLLECTED_MINE_REWARD 2
#define MAX_SQUARE_STEPS 40
#define MAX_SQUARES_TERMINAL
#define MAX_SQUARES 5
#endif